language: python
python:
  - "2.7"

before_install:
 - sudo apt-get install -qq libevent-dev

install:
 - "python setup.py install"
 - "pip install nose"

services:
  - redis-server

script: "make test"
